HAI 1.2
	VISIBLE "xvariable"
	I HAS A var2
	I HAS A x ITZ 5.5
	I HAS A x3 ITZ SUM OF 35.5 AN 5
	BTW SUM OF x5 AN 89.7
	BOTH SAEM 3.5 AN y
	y R 5
	DIFFRINT 5 AN 3.5
	OBTW hahahaha
	TLDR
	BTW single comment! wohoo
	BOTH OF x5 AN x2
	BOTH SAEM x3 AN BIGGR OF x3 AN y3
	EITHER OF BOTH OF x AN y AN x
	DIFFRINT x AN SMALLR OF x AN y
	BOTH OF EITHER OF WIN AN FAIL AN WIN
	O RLY?
	YA RLY
		VISIBLE x
	NO WAI
		VISIBLE y
	OIC
KTHXBYE